#spring.application.name=gen_code_ai
#server.port = 8081

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cinema_management"
    username: root
    password: Khanhcb11
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
